## Data analysis 

- Python is a powerful and flexible programming language ,but it doesn't have built in functions for mathematical 
ananlysis or data vissualization. For most data ananlysis we will rely on some of helpful libraries . we will explore 
we will explore 3 libraries which are use for data ananlysis and vissualization

## Data ananlysis steps 

- Ask Question(ask questions from data ).
- Wrangle Data (gathering data , asses it , clean it).
- Perform EDA (Exploring data and finding trends).
- Draw conclusion (Concluding from present data) and pridiction (pridicting from present data and conclusion of present data).
- Communicate Your Results (Communicate your research with head).

### Main charactersitics of Ndarray
- Array is ordered (we can do slicing).
- Array is mutable (we can do changing).
- Array is homogenous(only caters one data type).
- Due to array we can perform advance mathematical operations. 

In [1]:
import numpy as np 

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
np.ndim(arr)

1

In [8]:
# Scalar Matrix --> 0 dimension 
arr = np.array([1])
print(arr)

[1]


In [6]:
np.ndim(arr)

1

In [13]:
D_2 = np.array([[1,2,3],[2,3,4]])
print(D_2)
print( "Dimension :" , np.ndim(D_2))

[[1 2 3]
 [2 3 4]]
Dimension : 2


In [2]:
D_3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(D_3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [3]:
np.ndim(D_3)

3

## Note
- Next Dimension = Big Box having one or more than one small Boxes
- Previous = Small Box 

In [4]:
type(D_3)

numpy.ndarray

In [5]:
np.size(D_3)

12

## Array  vs List 

#### Deiffrence No.1 : Speed 

In [8]:
arr = np.arange(100000)
arr[-5:]

array([99995, 99996, 99997, 99998, 99999])

In [11]:
# Numpy
arr = np.arange(1000000)
%time for i in range(10) :arr2 = arr*2

Wall time: 26 ms


In [13]:
# Simple python list 
lst  = list(range(1000000))
%time for i in range(10) : lst2 = [element*2 for element in lst ]

Wall time: 1.2 s


- List comprehension ==> list(Final output) ==> cater loops , condition , expression.

#### Diffrence No.2 : Shape 

In [2]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
list_of_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
arr = np.array(list_of_lists)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.shape(list_of_lists)

(3, 3)

In [5]:
np.shape(arr)

(3, 3)

- Array requires rectangular shape 

In [16]:
Nrec = [[1,2,3],[4,5],[6,7,8,9]]
Nrec

[[1, 2, 3], [4, 5], [6, 7, 8, 9]]

In [7]:
np.shape(Nrec)

(3,)

In [9]:
arr1 = np.array(Nrec)
arr1

array([list([1, 2, 3]), list([4, 5]), list([6, 7, 8, 9])], dtype=object)

In [18]:
np.shape(arr1)   # vector Quantity 

(3,)

In [12]:
type(arr1[0])

list

In [13]:
type1 = arr1.dtype
print(type1)

object


In [17]:
np.size(arr1)   # size --> tells no.of elements 

3

In [15]:
np.size(Nrec)

3

In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.shape(arr)

(9,)

In [21]:
arr.shape

(9,)

In [24]:
arr.shape = (3,3)   # shape alteration 
arr.shape

(3, 3)

arr

#####  Homogenous vs Hetrogenous 

In [26]:
arr1 = np.array([1,0.2,0.4,"shahzaib",True])
arr1

array(['1', '0.2', '0.4', 'shahzaib', 'True'], dtype='<U32')

In [28]:
lst = [1,2.3,True,"shahzaib"]
lst

[1, 2.3, True, 'shahzaib']

In [30]:
arr1.dtype

dtype('<U32')

In [43]:
lst = np.array([1.3,2.6,7.8,9,10,11]) 
lst

array([ 1.3,  2.6,  7.8,  9. , 10. , 11. ])

In [6]:
Y = np.array([1.2,4.5,6.7,8.6] , dtype = np.int64)
print(Y)
print()
print("Data type:" , Y.dtype)

[1 4 6 8]

Data type: int64


### For checking Numpy Version

In [3]:
!conda list numpy 

# packages in environment at C:\Users\MEMONS\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.18.5           py38h6530119_0  
numpy-base                1.18.5           py38hc3f5095_0  
numpydoc                  1.1.0                      py_0  


In [1]:
import time 

In [12]:
x = np.random.random(1000000)
# genrate 1 lakh random floats b/w 0(inclusive) - 1(exclusive)

In [17]:
# simple python  
start = time.time()
y = sum(x) / len(x)
print(time.time() - start ) # by this we can calculate the time of this operation.(in python)

0.2191452980041504


In [18]:
y  # mean of lakh numbers 

0.5000423595502949

In [24]:
# numpy 
start = time.time()
y = np.mean(x)
print(time.time() - start ) # time of this operation. (in numpy)

0.0020003318786621094


In [25]:
y

0.5000423595502885

In [3]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [4]:
print("Type:" , type(x))
print('\n' ,"Data type:" ,x.dtype) 

Type: <class 'numpy.ndarray'>

 Data type: int32


In [5]:
x.shape  # no.if elements(in row) , no.of elements in column

(5,)

In [6]:
x.size  # total number of elements in matrix/array

5

In [7]:
Y = np.array([[1,2,3],[4,5,6]])
print(Y)

[[1 2 3]
 [4 5 6]]


In [8]:
Y.shape

(2, 3)

In [9]:
Y.size

6

In [10]:
# 1D array = rank1 aaray 
# 2D array = rank2 array 
# and so on

In [12]:
x = np.array(['Hello', 'world'])
print(x)

['Hello' 'world']


In [14]:
print('Shape:' , x.shape)
print('\n', "Size:" , x.size)
print('\n', "Type of structure:"  , type(x))
print('\n' , "Data type:"  , x.dtype )

Shape: (2,)

 Size: 2

 Type of structure: <class 'numpy.ndarray'>

 Data type: <U5


In [21]:
x = np.array([1,2.3,"shahzaib"])   # upcasting --> when python by itself change the data type of an array 
print(x)
print('Data type: ', x.dtype)

['1' '2.3' 'shahzaib']
Data type:  <U32


In [19]:
y = np.array([1.5,2.2,3.7], dtype = np.int64 ) # typecasting --> when we change the data type of an array by ourself
print(y)
print('Data type:' , y.dtype)

[1 2 3]
Data type: int64


### Built-in Functions to create ndarrays 

In [1]:
# These Functions are use to create dummy arrays for doing practice 

In [3]:
X = np.zeros((3,4)) # Zero array with specified shape 
print(X)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
X.dtype

dtype('float64')

In [6]:
X = np.zeros((3,4), dtype = int )
print(X)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
X.dtype

dtype('int32')

In [8]:
Y = np.ones((4,5))  # Ones array with specified shape 
print(Y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
Z = np.full((5,6), 5 , dtype = float )  # array with specied value and specified shape 
print(Z)             

[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


#### Arange Function 
- Provide 1d array with start , stop , step/interval
- Only for integers value 

In [21]:
# with only one argument 
np.arange(11)  # it is only stop and which is exclusive 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
# with 2 arguments 
np.arange(1,11) # start , stop(stop is exclusive )

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
# with 3 arguments 
np.arange(1,11,2)   # in this step is 2 

array([1, 3, 5, 7, 9])

### Linspace 
- use for non integers values 
- both Start and Stop are inclusive \
- Required Atleast 2 arguments 
- N / total numbers by deffault is 50 

In [22]:
np.linspace(0,25,10)

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [23]:
np.linspace(1,25,25)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

In [24]:
# Making stop excluded
np.linspace(0 , 25 , 10 , endpoint = False )

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5])

In [8]:
x = np.linspace(1,50)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [31]:
len(x)

50

#### Identity Matrix
- square matrix 
- diagonal with numbers and elesewhere 0s

In [34]:
np.eye(5)  # it gives 5 by 5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

- Changing arange and linspace arrays in rank2 array

In [36]:
X = np.arange(20)
X 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
Y = np.reshape(X , (2,10))  # 4*5 = 20 
Y                          # we have to choose those number pair which multiplication gives us size of array.
                           # pair(a,b) , a * b = len 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [42]:
# We can apply reshape function as method in any other function(arange , linspace) with dote(.) notation

In [43]:
X = np.arange(20).reshape(4,5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [47]:
Y = np.linspace(0 , 25 , 10 , endpoint  = False ).reshape((2,5))
print(Y)

[[ 0.   2.5  5.   7.5 10. ]
 [12.5 15.  17.5 20.  22.5]]


## Random Functions 

- It is use to make large dummy data.
- Use in Machine Learning.
- Numbers are not randomly genrate ;they genrate through a computer algorithm and these number are called 
 **psuedorandom**.
 - NumPy Library -->  Random Module  -->  Functions 

In [3]:
X = np.random.random((4,4))
print(X)

[[0.67852404 0.91699644 0.94520236 0.70727891]
 [0.54565391 0.11391066 0.3050275  0.83511622]
 [0.99248084 0.7783494  0.09897275 0.62780811]
 [0.27207023 0.97123407 0.73857365 0.33211176]]


###### Random Integers within a particular interval.

In [7]:
X = np.random.randint(4,15,(4,5)) # 15 is exclusive 
print(X)

[[ 5  4 13  4  8]
 [ 8 14  5  6  4]
 [13  9  4  7 13]
 [ 6  9  8 12  7]]


#### Random Arrays that satifies certain statistical properties.

- Consider random array with an mean of 0 and standard deviation of 0.1

In [10]:
X = np.random.normal(0,0.1,(100,100)) # mean , standard deviation , shape
X[:5,:5]

array([[-0.10288395, -0.20080725, -0.01808114, -0.01978645,  0.08084347],
       [ 0.02862096,  0.11283116, -0.08427528,  0.06854511,  0.0984653 ],
       [ 0.32395655,  0.04575438, -0.1075365 , -0.14977888, -0.0433895 ],
       [-0.02134155,  0.17215838,  0.36984226, -0.17499115,  0.17559443],
       [-0.05540787,  0.00751458,  0.09202133, -0.05103256,  0.21319736]])

In [13]:
print('Mean: ', X.mean())  # mean will be close to 0 
print()
print("Standard Deviation :" , X.std())
print()
print("Max: ", X.max())
print()
print('Minimum: ', X.min())
print()
print("Positive :" , (X>0).sum())   # len  of all postive numbers
print()
print("Negative :" , (X<0).sum())   # len of all negative numbers

Mean:  -0.0004737709803018242

Standard Deviation : 0.09977268942555997

Max:  0.44319531215750624

Minimum:  -0.329664474085167

Positive : 5013

Negative : 4987


In [16]:
# python often provide answer as approximation 

In [17]:
# Homework 
# using the built-in function make 4X4 ndarray that only conatin consective odd numbers from 1 - 33 (inclusive)

In [4]:
Y = np.arange(1,32,2)
Y

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [5]:
Z = np.reshape(Y,(4,4))
Z

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23],
       [25, 27, 29, 31]])

In [6]:
np.shape(Z)

(4, 4)

### Practice

In [10]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(x)
print()
print("Dimension:" , np.ndim(x))
print()
print("Size:" , np.size(x))
print()
print("Shape:" , np.shape(x))
print()
print("Type:" ,type(x) )
print()
print("Data Type:" , x.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]

Dimension: 3

Size: 12

Shape: (1, 4, 3)

Type: <class 'numpy.ndarray'>

Data Type: int32


In [11]:
list_of_lists = [[1,2],[3,4,5],[6,7,8,9]]
list_of_lists

[[1, 2], [3, 4, 5], [6, 7, 8, 9]]

In [12]:
Y = np.array(list_of_lists)
Y

array([list([1, 2]), list([3, 4, 5]), list([6, 7, 8, 9])], dtype=object)

In [13]:
np.size(Y)

3

In [15]:
Y = np.random.random(90000)

In [18]:
import time

In [20]:
#simple python
start_time = time.time()
Z = sum(Y) / len(Y)
print(time.time() - start_time)

0.03702378273010254


In [21]:
# numpy
start_time = time.time()
T = np.mean(Y)
print(time.time() - start_time)

0.001001596450805664


In [24]:
A = np.zeros((4,4) , dtype = int)
A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
B = np.ones((6,9) , dtype = float )
B

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
Q = np.full((4,5) , 8 ,dtype = int)
Q

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [27]:
Y = np.arange(1,10,5)
Y

array([1, 6])

In [30]:
T = np.arange(1,90 , 11)
T

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [33]:
W = np.linspace(3,20 , 18 , endpoint = False )
W

array([ 3.        ,  3.94444444,  4.88888889,  5.83333333,  6.77777778,
        7.72222222,  8.66666667,  9.61111111, 10.55555556, 11.5       ,
       12.44444444, 13.38888889, 14.33333333, 15.27777778, 16.22222222,
       17.16666667, 18.11111111, 19.05555556])

In [34]:
W = np.arange(1,10).reshape(3,3)
W

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
Q = np.linspace(2,90,10, endpoint = False).reshape(5,2)
Q

array([[ 2. , 10.8],
       [19.6, 28.4],
       [37.2, 46. ],
       [54.8, 63.6],
       [72.4, 81.2]])

In [38]:
E = np.eye(9)
E

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
T  = np.diag([12,3,4,5,6,7,7,8,0])
T

array([[12,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  7,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [3]:
X = np.random.random((3,4))
X

array([[0.23114144, 0.9699851 , 0.84169927, 0.37404464],
       [0.38492478, 0.49117227, 0.86169068, 0.60898475],
       [0.07190172, 0.71008184, 0.73866287, 0.49029803]])

In [5]:
Y = np.random.randint(1,10, (5,7))
Y

array([[6, 7, 6, 2, 8, 3, 1],
       [9, 5, 7, 8, 6, 1, 2],
       [6, 4, 3, 8, 9, 8, 1],
       [1, 6, 2, 4, 8, 9, 6],
       [7, 6, 7, 1, 3, 9, 5]])

In [8]:
Z = np.random.normal(1 , 0.1 , (100,100 ))
Z[:5,:5]

array([[1.45499976, 1.09671623, 0.99637567, 0.40719928, 0.65410206],
       [0.5390134 , 1.08929865, 1.40032293, 0.72051198, 0.77037427],
       [1.07478295, 1.39940132, 0.92788708, 0.97209886, 1.23695655],
       [0.32343155, 0.81801676, 0.88646637, 1.16884265, 1.54001366],
       [0.95963688, 0.96050199, 0.7613364 , 1.28125783, 0.74341794]])

In [9]:
print("Mean:" , np.mean(Z))
print("Standard deviation : " , np.std(Z))
print("Maximum :" , np.max(Z))
print("Minimum:" , np.min(Z))
print("Positive:" ,(Z>0).sum() )
print("Negative:" , (Z<0).sum())

Mean: 0.9958095117749218
Standard deviation :  0.30615766470681366
Maximum : 2.243283935492596
Minimum: -0.16731699082628526
Positive: 9994
Negative: 6
