In [5]:
new = [] 
def Upgrade(A,B):
    for i in A:
        new.append(i+(i*B))
    print(new)

In [6]:
salary = [100,200,300]

In [7]:
Upgrade(salary,0.1)

[110.0, 220.0, 330.0]


In [8]:
jobs = [
    "Financial Data Analyst",
    "Marketing Data Analyst",
    "Healthcare Data Analyst",
    "Operations Data Analyst",
    "Business Data Analyst",
    "Marine Biologist",
    "Structural Engineer",
    "Executive Chef",
    "Flight Instructor",
    "Landscape Architect"
]

In [11]:
new = [] 
for i in jobs:
    if "Data Analyst" in i:
        new.append(i)
print(new)

['Financial Data Analyst', 'Marketing Data Analyst', 'Healthcare Data Analyst', 'Operations Data Analyst', 'Business Data Analyst']


In [12]:
years = {"Shahzaib": 5, "Asad" : 7, "Arfa" : 11 , "Asif"  : 9}

In [13]:
for key,value in years.items():
    if value > 5:
        print(f"{key} has {value} years of expierence")

Asad has 7 years of expierence
Arfa has 11 years of expierence
Asif has 9 years of expierence


In [16]:
for i in range(1,10):
    if i == 5:
        break 
    print(i)

1
2
3
4


In [21]:
n = int(input("num:"))
sum = 0
for i in range(1,n+1):
    if i <= n:
        sum += i
print(sum)
    

num: 10


55


In [23]:
n = int(input("num:"))
sum = 0 
i =1 
while i <= n:
    sum += i 
    i += 1
print(sum)

num: 10


55


In [24]:
 five =lambda x : x *5

In [25]:
five(5)

25

In [26]:
(lambda x ,y,z : x *8 +(y/4) -z *4)(4,5,6)

9.25

In [28]:
# Define data science job roles and required skills
job_roles = [
    {'role': 'Data Analyst', 'skills': ['Python', 'SQL', 'Excel']},
    {'role': 'Data Scientist', 'skills': ['Python', 'R', 'Machine Learning', 'Deep Learning']},
    {'role': 'Machine Learning Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Scikit-Learn']},
    {'role': 'Data Engineer', 'skills': ['Python', 'Apache Spark', 'Hadoop', 'SQL']},
    {'role': 'Business Intelligence Analyst', 'skills': ['Python', 'SQL', 'Tableau', 'Power BI', 'Excel']},
    {'role': 'Quantitative Analyst', 'skills': ['R', 'Python', 'MATLAB', 'Statistics']},
    {'role': 'Operations Analyst', 'skills': ['Python', 'SQL', 'Data Visualization', 'Process Improvement']},
    {'role': 'Database Administrator', 'skills': ['SQL', 'Oracle', 'MySQL', 'Database Management']},
    {'role': 'AI Engineer', 'skills': ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision']},
    {'role': 'Statistician', 'skills': ['R', 'SAS', 'Python', 'Statistical Modeling']}
]
# My skills
my_skills = ['Python', 'SQL', 'Excel']

In [30]:
for i in job_roles:
    print(i["role"])

Data Analyst
Data Scientist
Machine Learning Engineer
Data Engineer
Business Intelligence Analyst
Quantitative Analyst
Operations Analyst
Database Administrator
AI Engineer
Statistician


In [33]:
new = [] 
for job in job_roles:
    if all(i in job["skills"] for i in my_skills):
        new.append(job["role"])
print(new)

['Data Analyst', 'Business Intelligence Analyst']


In [34]:
import random 

In [37]:
salary_list = [random.randint(100,2000) for i in range(1,20)]
print(salary_list)

[1745, 766, 365, 1385, 345, 1804, 896, 946, 1290, 1329, 1539, 324, 1988, 837, 1510, 1305, 402, 1914, 931]


In [38]:
import statistics 

In [44]:
print(round(statistics.mean(salary_list),2))
statistics.quantiles(salary_list)

1137.95


[766.0, 1290.0, 1539.0]

In [45]:
import numpy as np 

In [46]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l3 = [9,10,11,12]
array = np.array([[l1,l2,l3]])
print(array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [47]:
array.shape

(1, 3, 4)

In [49]:
ar1 = np.zeros((3,4))
print(ar1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [51]:
ar2 = np.eye(3)
print(ar2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
